- hosts: cluster

  tasks:

  - name: Copy addCephUser.sh
    copy:
      src: addCephUser.sh
      dest: /
      mode: '0777'

  - name: Chmod +x /addCephUser.sh
    command: chmod +x /addCephUser.sh

  - name: start addCephUser.sh
    command: sh /addCephUser.sh
