- hosts: all

  tasks:

  - name: Update system
    command: yum update -y

  - name: Install epele-release
    yum:
      name: epel-release
      state: present

  - name: Install nano
    yum:
      name: nano
      state: present

  - name: Install epel-release
    yum:
      name: wget
      state: present

  - name: Disable selinux
    command: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
    
  - name: Copy hosts
    copy:
      src: data/hosts
      dest: /etc/
      mode: '0777'

  - firewalld:
      port: 6789/tcp
      permanent: yes
      state: enabled

  - firewalld:
      port: 4505-4506/tcp
      permanent: yes
      state: enabled

  - firewalld:
      port: 2003/tcp
      permanent: yes
      state: enabled

  - firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled    
